
enum IPCMainToRenderChannelName {
	MAIN_INFO = "MAIN_INFO",
	DISPLAY_MASK_NOTIFICATION = "DISPLAY_MASK_NOTIFICATION",

	// hotUpdateDialogWindow专用的ipc
	HOT_UPDATE_DIALOG_INFO_UPDATE = "HOT_UPDATE_DIALOG_INFO_UPDATE",
	// alertDialogWindow专用的ipc
	MAIN_ALERT_DIALOG_INFO_UPDATE = "MAIN_ALERT_DIALOG_INFO_UPDATE"

}

enum IPCRendererToMainChannelName {
	RENDERER_READY = "RENDERER_READY",
	OPEN_DEV_TOOL = "OPEN_DEV_TOOL",
	OPEN_URL = "OPEN_URL",
	GET_WEB_LINKS = "GET_WEB_LINKS",
	SAVE_WEB_LINK = "SAVE_WEB_LINK",
	DELETE_WEB_LINK = "DELETE_WEB_LINK",
	GET_CURRENT_LINK = "GET_CURRENT_LINK",
	SET_CURRENT_LINK = "SET_CURRENT_LINK",

	// hotUpdateDialogWindow专用的ipc
	HOT_UPDATE_DIALOG_CALLBACK = "HOT_UPDATE_DIALOG_CALLBACK",
	// alertDialogWindow专用的ipc
	MAIN_ALERT_DIALOG_CALLBACK = "MAIN_ALERT_DIALOG_CALLBACK",
}


export {
	IPCMainToRenderChannelName,
	IPCRendererToMainChannelName,
};